## Análisis exploratorio inicial del dataset
Objetivo: comprender la estructura, calidad y variables del dataset
procedente del Austin Animal Center.

In [1]:
import pandas as pd

In [2]:
datos = pd.read_csv("aac_intakes_outcomes.csv")

In [3]:
datos.head()

,age_upon_outcome,animal_id_outcome,date_of_birth,outcome_subtype,outcome_type,sex_upon_outcome,age_upon_outcome_(days),age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,...,age_upon_intake_age_group,intake_datetime,intake_month,intake_year,intake_monthyear,intake_weekday,intake_hour,intake_number,time_in_shelter,time_in_shelter_days
0,10 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,3650,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,...,"(7.5, 10.0]",2017-12-07 00:00:00,12,2017,2017-12,Thursday,14,1.0,0 days 14:07:00.000000000,0.588194
1,7 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2555,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,...,"(5.0, 7.5]",2014-12-19 10:21:00,12,2014,2014-12,Friday,10,2.0,1 days 06:14:00.000000000,1.259722
2,6 years,A006100,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2190,6.0,"(5.0, 7.5]",2014-03-08 17:10:00,...,"(5.0, 7.5]",2014-03-07 14:26:00,3,2014,2014-03,Friday,14,3.0,1 days 02:44:00.000000000,1.113889
3,10 years,A047759,2004-04-02 00:00:00,Partner,Transfer,Neutered Male,3650,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,...,"(7.5, 10.0]",2014-04-02 15:55:00,4,2014,2014-04,Wednesday,15,1.0,4 days 23:17:00.000000000,4.970139
4,16 years,A134067,1997-10-16 00:00:00,NaN,Return to Owner,Neutered Male,5840,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,...,"(15.0, 17.5]",2013-11-16 09:02:00,11,2013,2013-11,Saturday,9,1.0,0 days 02:52:00.000000000,0.119444

In [4]:
datos.shape

(79672, 41)

In [5]:
datos.info

<bound method DataFrame.info of       age_upon_outcome animal_id_outcome        date_of_birth outcome_subtype  \
0             10 years           A006100  2007-07-09 00:00:00             NaN
1              7 years           A006100  2007-07-09 00:00:00             NaN
2              6 years           A006100  2007-07-09 00:00:00             NaN
3             10 years           A047759  2004-04-02 00:00:00         Partner
4             16 years           A134067  1997-10-16 00:00:00             NaN
...                ...               ...                  ...             ...
79667          2 weeks           A769060  2018-03-14 00:00:00         Partner
79668          2 years           A769064  2016-03-29 00:00:00     Rabies Risk
79669           1 year           A769065  2017-03-29 00:00:00     Rabies Risk
79670        10 months           A769066  2017-05-01 00:00:00             NaN
79671         10 years           A769067  2008-03-29 00:00:00       Suffering

          outcome_type sex_upon_outcome  age_upon_outcome_(days)  \
0      Return to Owner    Neutered Male                     3650
1      Return to Owner    Neutered Male                     2555
2      Return to Owner    Neutered Male                     2190
3             Transfer    Neutered Male                     3650
4      Return to Owner    Neutered Male                     5840
...                ...              ...                      ...
79667         Transfer          Unknown                       14
79668       Euthanasia          Unknown                      730
79669       Euthanasia          Unknown                      365
79670  Return to Owner      Intact Male                      300
79671       Euthanasia    Spayed Female                     3650

       age_upon_outcome_(years) age_upon_outcome_age_group  \
0                     10.000000                (7.5, 10.0]
1                      7.000000                 (5.0, 7.5]
2                      6.000000                 (5.0, 7.5]
3                     10.000000                (7.5, 10.0]
4                     16.000000               (15.0, 17.5]
...                         ...                        ...
79667                  0.038356              (-0.025, 2.5]
79668                  2.000000              (-0.025, 2.5]
79669                  1.000000              (-0.025, 2.5]
79670                  0.821918              (-0.025, 2.5]
79671                 10.000000                (7.5, 10.0]

          outcome_datetime  ...  age_upon_intake_age_group  \
0      2017-12-07 14:07:00  ...                (7.5, 10.0]
1      2014-12-20 16:35:00  ...                 (5.0, 7.5]
2      2014-03-08 17:10:00  ...                 (5.0, 7.5]
3      2014-04-07 15:12:00  ...                (7.5, 10.0]
4      2013-11-16 11:54:00  ...               (15.0, 17.5]
...                    ...  ...                        ...
79667  2018-03-29 18:14:00  ...              (-0.025, 2.5]
79668  2018-03-29 18:30:00  ...              (-0.025, 2.5]
79669  2018-03-29 18:28:00  ...              (-0.025, 2.5]
79670  2018-03-31 12:37:00  ...              (-0.025, 2.5]
79671  2018-03-30 13:52:00  ...                (7.5, 10.0]

           intake_datetime intake_month intake_year  intake_monthyear  \
0      2017-12-07 00:00:00           12        2017           2017-12
1      2014-12-19 10:21:00           12        2014           2014-12
2      2014-03-07 14:26:00            3        2014           2014-03
3      2014-04-02 15:55:00            4        2014           2014-04
4      2013-11-16 09:02:00           11        2013           2013-11
...                    ...          ...         ...               ...
79667  2018-03-29 16:23:00            3        2018           2018-03
79668  2018-03-29 17:13:00            3        2018           2018-03
79669  2018-03-29 17:19:00            3        2018           2018-03
79670  2018-03-29 18:19:00            3        2018           2018-03
79671  2018-03-29 18:20:00            3        2018           2018-03

       intake_weekday  intake_hour  intake_number            time_in_shelter  \
0            Thursday           14            1.0  0 days 14:07:00.000000000
1              Friday           10            2.0  1 days 06:14:00.000000000
2              Friday           14            3.0  1 days 02:44:00.000000000
3           Wednesday           15            1.0  4 days 23:17:00.000000000
4            Saturday            9            1.0  0 days 02:52:00.000000000
...               ...          ...            ...                        ...
79667        Thursday           16            1.0  0 days 01:51:00.000000000
79668        Thursday           17            1.0  0 days 01:17:00.000000000
79669        Thursday           17            1.0  0 days 01:09:00.000000000
79670        Thursday           18            1.0  1 days 18:18:00.000000000
79671        Thursday           18            1.0  0 days 19:32:00.000000000

      time_in_shelter_days
0                 0.588194
1                 1.259722
2                 1.113889
3                 4.970139
4                 0.119444
...                    ...
79667             0.077083
79668             0.053472
79669             0.047917
79670             1.762500
79671             0.813889

[79672 rows x 41 columns]>

In [6]:
datos.dtypes

age_upon_outcome               object
animal_id_outcome              object
date_of_birth                  object
outcome_subtype                object
outcome_type                   object
sex_upon_outcome               object
age_upon_outcome_(days)         int64
age_upon_outcome_(years)      float64
age_upon_outcome_age_group     object
outcome_datetime               object
outcome_month                   int64
outcome_year                    int64
outcome_monthyear              object
outcome_weekday                object
outcome_hour                    int64
outcome_number                float64
dob_year                        int64
dob_month                       int64
dob_monthyear                  object
age_upon_intake                object
animal_id_intake               object
animal_type                    object
breed                          object
color                          object
found_location                 object
intake_condition               object
intake_type                    object
sex_upon_intake                object
count                           int64
age_upon_intake_(days)          int64
age_upon_intake_(years)       float64
age_upon_intake_age_group      object
intake_datetime                object
intake_month                    int64
intake_year                     int64
intake_monthyear               object
intake_weekday                 object
intake_hour                     int64
intake_number                 float64
time_in_shelter                object
time_in_shelter_days          float64
dtype: object

**Eliminar columnas**:

Las columnas "animal_id_outcome" y "animal_id_intake" tienen los mismos valores ya que el animal solo genera un id. Eliminaremos una.

Las columnas "outcome_number" y "intake_number" tienen los mismos valores ya que es el número de veces que animal ha estado en el refugio. Eliminaremos una.

In [7]:
cols_to_drop = [
    "animal_id_outcome",
    "outcome_number"
]

datos2 = datos.drop(columns=cols_to_drop)

In [8]:
datos2.head()

,age_upon_outcome,date_of_birth,outcome_subtype,outcome_type,sex_upon_outcome,age_upon_outcome_(days),age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,outcome_month,...,age_upon_intake_age_group,intake_datetime,intake_month,intake_year,intake_monthyear,intake_weekday,intake_hour,intake_number,time_in_shelter,time_in_shelter_days
0,10 years,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,3650,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,12,...,"(7.5, 10.0]",2017-12-07 00:00:00,12,2017,2017-12,Thursday,14,1.0,0 days 14:07:00.000000000,0.588194
1,7 years,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2555,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,12,...,"(5.0, 7.5]",2014-12-19 10:21:00,12,2014,2014-12,Friday,10,2.0,1 days 06:14:00.000000000,1.259722
2,6 years,2007-07-09 00:00:00,NaN,Return to Owner,Neutered Male,2190,6.0,"(5.0, 7.5]",2014-03-08 17:10:00,3,...,"(5.0, 7.5]",2014-03-07 14:26:00,3,2014,2014-03,Friday,14,3.0,1 days 02:44:00.000000000,1.113889
3,10 years,2004-04-02 00:00:00,Partner,Transfer,Neutered Male,3650,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,4,...,"(7.5, 10.0]",2014-04-02 15:55:00,4,2014,2014-04,Wednesday,15,1.0,4 days 23:17:00.000000000,4.970139
4,16 years,1997-10-16 00:00:00,NaN,Return to Owner,Neutered Male,5840,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,11,...,"(15.0, 17.5]",2013-11-16 09:02:00,11,2013,2013-11,Saturday,9,1.0,0 days 02:52:00.000000000,0.119444

**Eliminar posibles duplicados**:

In [9]:
datos2.drop_duplicates(inplace=True)

**Sustituir valores desconocidos:**

La única variable con un porcentaje de valores desconocidos es "outcome_subtype" con un 54%. Se sustituirán con la palabra "Unknown".

In [10]:
datos2['outcome_subtype'] = datos2['outcome_subtype'].fillna('Unknown')

**Normalizamos texto**:

In [11]:
cols_to_strip = ["animal_type", "breed", "sex_upon_outcome", "color", "found_location", "intake_condition", "intake_type", "sex_upon_intake", "outcome_type", "outcome_subtype", "outcome_weekday", "intake_weekday"]
for col in cols_to_strip:
    datos2[col] = datos2[col].str.strip().str.title()

In [12]:
datos2.head()

,age_upon_outcome,date_of_birth,outcome_subtype,outcome_type,sex_upon_outcome,age_upon_outcome_(days),age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,outcome_month,...,age_upon_intake_age_group,intake_datetime,intake_month,intake_year,intake_monthyear,intake_weekday,intake_hour,intake_number,time_in_shelter,time_in_shelter_days
0,10 years,2007-07-09 00:00:00,Unknown,Return To Owner,Neutered Male,3650,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,12,...,"(7.5, 10.0]",2017-12-07 00:00:00,12,2017,2017-12,Thursday,14,1.0,0 days 14:07:00.000000000,0.588194
1,7 years,2007-07-09 00:00:00,Unknown,Return To Owner,Neutered Male,2555,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,12,...,"(5.0, 7.5]",2014-12-19 10:21:00,12,2014,2014-12,Friday,10,2.0,1 days 06:14:00.000000000,1.259722
2,6 years,2007-07-09 00:00:00,Unknown,Return To Owner,Neutered Male,2190,6.0,"(5.0, 7.5]",2014-03-08 17:10:00,3,...,"(5.0, 7.5]",2014-03-07 14:26:00,3,2014,2014-03,Friday,14,3.0,1 days 02:44:00.000000000,1.113889
3,10 years,2004-04-02 00:00:00,Partner,Transfer,Neutered Male,3650,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,4,...,"(7.5, 10.0]",2014-04-02 15:55:00,4,2014,2014-04,Wednesday,15,1.0,4 days 23:17:00.000000000,4.970139
4,16 years,1997-10-16 00:00:00,Unknown,Return To Owner,Neutered Male,5840,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,11,...,"(15.0, 17.5]",2013-11-16 09:02:00,11,2013,2013-11,Saturday,9,1.0,0 days 02:52:00.000000000,0.119444

**Convertir fechas a datetime y extraer solo la fecha**:

In [13]:
datos2['intake_datetime'] = pd.to_datetime(datos2['intake_datetime'])
datos2['outcome_datetime'] = pd.to_datetime(datos2['outcome_datetime'])
datos2['intake_date'] = datos2['intake_datetime'].dt.date
datos2['outcome_date'] = datos2['outcome_datetime'].dt.date

In [14]:
datos2.head()

,age_upon_outcome,date_of_birth,outcome_subtype,outcome_type,sex_upon_outcome,age_upon_outcome_(days),age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,outcome_month,...,intake_month,intake_year,intake_monthyear,intake_weekday,intake_hour,intake_number,time_in_shelter,time_in_shelter_days,intake_date,outcome_date
0,10 years,2007-07-09 00:00:00,Unknown,Return To Owner,Neutered Male,3650,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,12,...,12,2017,2017-12,Thursday,14,1.0,0 days 14:07:00.000000000,0.588194,2017-12-07,2017-12-07
1,7 years,2007-07-09 00:00:00,Unknown,Return To Owner,Neutered Male,2555,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,12,...,12,2014,2014-12,Friday,10,2.0,1 days 06:14:00.000000000,1.259722,2014-12-19,2014-12-20
2,6 years,2007-07-09 00:00:00,Unknown,Return To Owner,Neutered Male,2190,6.0,"(5.0, 7.5]",2014-03-08 17:10:00,3,...,3,2014,2014-03,Friday,14,3.0,1 days 02:44:00.000000000,1.113889,2014-03-07,2014-03-08
3,10 years,2004-04-02 00:00:00,Partner,Transfer,Neutered Male,3650,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,4,...,4,2014,2014-04,Wednesday,15,1.0,4 days 23:17:00.000000000,4.970139,2014-04-02,2014-04-07
4,16 years,1997-10-16 00:00:00,Unknown,Return To Owner,Neutered Male,5840,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,11,...,11,2013,2013-11,Saturday,9,1.0,0 days 02:52:00.000000000,0.119444,2013-11-16,2013-11-16

**Creación de indicadores binarios**:

In [15]:
datos2['outcome_type'].value_counts()

outcome_type
Adoption           33583
Transfer           23791
Return To Owner    14784
Euthanasia          6238
Died                 690
Disposal             301
Rto-Adopt            179
Missing               46
Relocate              15
Unknown               10
Name: count, dtype: int64

In [16]:
datos2['IsAdopted'] = (datos2['outcome_type'] == 'Adoption').astype(int)
datos2['IsEuthanized'] = (datos2['outcome_type'] == 'Euthanasia').astype(int)
datos2['IsReturned'] = datos2['outcome_type'].str.contains(
    'return to owner|rto',
    case=False,
    na=False
).astype(int)
datos2['IsSick'] = (datos2['intake_condition'] == 'Sick').astype(int)
datos2['IsInjured'] = (datos2['intake_condition'] == 'Injured').astype(int)
datos2['IsRescue'] = (datos2['intake_type'] == 'Stray').astype(int)
datos2["Reentry"] = (datos2["intake_number"] > 1).astype(int)
datos2["Istransfer"] = (datos2["outcome_type"] == "Transfer").astype(int)

In [17]:
datos2.head()

,age_upon_outcome,date_of_birth,outcome_subtype,outcome_type,sex_upon_outcome,age_upon_outcome_(days),age_upon_outcome_(years),age_upon_outcome_age_group,outcome_datetime,outcome_month,...,outcome_date,IsAdopted,IsEuthanized,IsReturned,IsSick,IsInjured,IsRescue,Reentry,Istransfer,Isbehavior
0,10 years,2007-07-09 00:00:00,Unknown,Return To Owner,Neutered Male,3650,10.0,"(7.5, 10.0]",2017-12-07 14:07:00,12,...,2017-12-07,0,0,1,0,0,1,0,0,0
1,7 years,2007-07-09 00:00:00,Unknown,Return To Owner,Neutered Male,2555,7.0,"(5.0, 7.5]",2014-12-20 16:35:00,12,...,2014-12-20,0,0,1,0,0,0,1,0,0
2,6 years,2007-07-09 00:00:00,Unknown,Return To Owner,Neutered Male,2190,6.0,"(5.0, 7.5]",2014-03-08 17:10:00,3,...,2014-03-08,0,0,1,0,0,0,1,0,0
3,10 years,2004-04-02 00:00:00,Partner,Transfer,Neutered Male,3650,10.0,"(7.5, 10.0]",2014-04-07 15:12:00,4,...,2014-04-07,0,0,0,0,0,0,0,1,0
4,16 years,1997-10-16 00:00:00,Unknown,Return To Owner,Neutered Male,5840,16.0,"(15.0, 17.5]",2013-11-16 11:54:00,11,...,2013-11-16,0,0,1,0,1,0,0,0,0

**Guardar el archivo en un nuevo CSV**:

In [ ]:
#datos2.to_csv(
    "datos_powerbi.csv",
    sep=";",        
    decimal=",",    
    index=False
#)